# Generated by Django 5.0.14 on 2026-09-09 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    (
                        "manage_users",
                        "Pode gerenciar usuários (criar, editar, ativar/desativar)",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="RoleProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição livre do cargo, exibida na tela de gestão de cargos.",
                    ),
                ),
                (
                    "is_protected",
                    models.BooleanField(
                        default=False,
                        help_text="Cargo do sistema que não pode ser editado/excluído pela interface (ex.: Administrador).",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "cargo",
                "verbose_name_plural": "cargos",
            },
        ),
    ]
