# Generated by Django 5.0.14 on 2026-09-14 13:42

import apps.attachments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ORCAMENTO_PROPOSTA", "Orçamento/Proposta"),
                            ("CONTRATO", "Contrato"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "Gerado pelo sistema"),
                            ("USER", "Enviado por usuário"),
                        ],
                        default="SYSTEM",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.attachments.models._attachment_upload_to
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "anexo",
                "verbose_name_plural": "anexos",
                "ordering": ["-created_at"],
                "permissions": [("view_attachments", "Pode ver anexos")],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="attachments_content_44d952_idx",
                    )
                ],
            },
        ),
    ]
