# Generated by Django 5.0.14 on 2026-08-20 12:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("clients", "0001_initial"),
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "patrimonio",
                    models.CharField(editable=False, max_length=40, unique=True),
                ),
                ("model_sequence", models.PositiveIntegerField(editable=False)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                (
                    "legacy_code",
                    models.CharField(
                        blank=True,
                        help_text="Código da planilha antiga, preservado só para rastreabilidade.",
                        max_length=100,
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=150)),
                ("acquisition_date", models.DateField(blank=True, null=True)),
                (
                    "acquisition_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("EM_OPERACAO", "Em operação"),
                            ("MANUTENCAO", "Manutenção"),
                            ("INATIVO", "Inativo"),
                        ],
                        default="DISPONIVEL",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("BOM", "Bom"),
                            ("MEDIO", "Médio"),
                            ("RUIM", "Ruim"),
                            ("INUTILIZAVEL", "Inutilizável"),
                        ],
                        default="BOM",
                        max_length=20,
                    ),
                ),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("last_cleaning_date", models.DateField(blank=True, null=True)),
                ("next_maintenance_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_with_client",
                        to="clients.client",
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_here",
                        to="operations.location",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.equipmentmodel",
                    ),
                ),
                (
                    "superseded_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "equipamento",
                "verbose_name_plural": "equipamentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEquipment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "patrimonio",
                    models.CharField(db_index=True, editable=False, max_length=40),
                ),
                ("model_sequence", models.PositiveIntegerField(editable=False)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                (
                    "legacy_code",
                    models.CharField(
                        blank=True,
                        help_text="Código da planilha antiga, preservado só para rastreabilidade.",
                        max_length=100,
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=150)),
                ("acquisition_date", models.DateField(blank=True, null=True)),
                (
                    "acquisition_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("EM_OPERACAO", "Em operação"),
                            ("MANUTENCAO", "Manutenção"),
                            ("INATIVO", "Inativo"),
                        ],
                        default="DISPONIVEL",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("BOM", "Bom"),
                            ("MEDIO", "Médio"),
                            ("RUIM", "Ruim"),
                            ("INUTILIZAVEL", "Inutilizável"),
                        ],
                        default="BOM",
                        max_length=20,
                    ),
                ),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("last_cleaning_date", models.DateField(blank=True, null=True)),
                ("next_maintenance_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalog.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_client",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="clients.client",
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="operations.location",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalog.equipmentmodel",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical equipamento",
                "verbose_name_plural": "historical equipamentos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(fields=["status"], name="equipment_e_status_fb8540_idx"),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["condition"], name="equipment_e_conditi_f417f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["category"], name="equipment_e_categor_3d1cd8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="equipment",
            constraint=models.UniqueConstraint(
                fields=("model", "model_sequence"), name="uniq_model_sequence_per_model"
            ),
        ),
    ]
