# Generated by Django 5.0.14 on 2026-08-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalequipment",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
    ]
