# Generated by Django 5.0.14 on 2026-08-21 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_alter_historicalequipment_history_change_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_value",
                    models.CharField(
                        choices=[
                            ("BOM", "Bom"),
                            ("MEDIO", "Médio"),
                            ("RUIM", "Ruim"),
                            ("INUTILIZAVEL", "Inutilizável"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_value",
                    models.CharField(
                        choices=[
                            ("BOM", "Bom"),
                            ("MEDIO", "Médio"),
                            ("RUIM", "Ruim"),
                            ("INUTILIZAVEL", "Inutilizável"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField()),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="condition_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_history",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "histórico de condição",
                "verbose_name_plural": "histórico de condição",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_value",
                    models.CharField(
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("EM_OPERACAO", "Em operação"),
                            ("MANUTENCAO", "Manutenção"),
                            ("INATIVO", "Inativo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_value",
                    models.CharField(
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("EM_OPERACAO", "Em operação"),
                            ("MANUTENCAO", "Manutenção"),
                            ("INATIVO", "Inativo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField()),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "histórico de status",
                "verbose_name_plural": "histórico de status",
                "ordering": ["-changed_at"],
            },
        ),
    ]
