# Generated by Django 5.0.14 on 2026-08-25 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_historicalequipmentmodel_history_change_reason"),
        ("equipment", "0003_conditionhistory_statushistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("BOM", "Bom"),
                            ("MEDIO", "Médio"),
                            ("RUIM", "Ruim"),
                            ("INUTILIZAVEL", "Inutilizável"),
                        ],
                        max_length=20,
                    ),
                ),
                ("first_patrimonio", models.CharField(max_length=40)),
                ("last_patrimonio", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment_batches_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment_batches",
                        to="catalog.equipmentmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "lote de cadastro de equipamentos",
                "verbose_name_plural": "lotes de cadastro de equipamentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="equipment",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment_items",
                to="equipment.equipmentbatch",
            ),
        ),
        migrations.AddField(
            model_name="historicalequipment",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="equipment.equipmentbatch",
            ),
        ),
    ]
