# Generated by Django 5.0.14 on 2026-08-25 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_historicalclient_remove_client_address_and_more"),
        ("equipment", "0004_equipmentbatch_equipment_batch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="current_client",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment_with_client",
                to="clients.client",
            ),
        ),
        migrations.AlterField(
            model_name="historicalequipment",
            name="current_client",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clients.client",
            ),
        ),
    ]
