# Generated by Django 5.0.14 on 2026-09-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0005_alter_equipment_current_client_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("manage_equipment", "Pode gerenciar equipamentos"),
                    (
                        "view_acquisition_value",
                        "Pode ver valor de aquisição do equipamento",
                    ),
                    (
                        "change_status_condition",
                        "Pode alterar status/condição do equipamento",
                    ),
                    ("add_photos", "Pode adicionar fotos/anexos de equipamento"),
                    ("export_data", "Pode exportar dados (etiquetas/QR codes)"),
                    (
                        "import_legacy_spreadsheet",
                        "Pode importar planilha legada de equipamentos",
                    ),
                    (
                        "supersede_equipment",
                        "Pode reemitir patrimônio (superseder equipamento)",
                    ),
                ],
                "verbose_name": "equipamento",
                "verbose_name_plural": "equipamentos",
            },
        ),
    ]
