# Generated by Django 5.0.14 on 2026-08-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumedSubmissionToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                (
                    "scope",
                    models.CharField(
                        help_text="Só para diagnóstico — qual formulário consumiu o token.",
                        max_length=150,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "token de submissão consumido",
                "verbose_name_plural": "tokens de submissão consumidos",
            },
        ),
    ]
