# Generated by Django 5.0.14 on 2026-09-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_consumedsubmissiontoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Razão social/nome da empresa.",
                        max_length=200,
                    ),
                ),
                ("cnpj", models.CharField(blank=True, max_length=20)),
                ("logradouro", models.CharField(blank=True, max_length=255)),
                ("numero", models.CharField(blank=True, max_length=20)),
                ("bairro", models.CharField(blank=True, max_length=100)),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("uf", models.CharField(blank=True, max_length=2)),
                ("cep", models.CharField(blank=True, max_length=9)),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Telefone fixo.", max_length=30
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(blank=True, help_text="Celular.", max_length=30),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "verbose_name": "dados da empresa",
                "verbose_name_plural": "dados da empresa",
                "permissions": [],
            },
        ),
    ]
