# Generated by Django 5.0.14 on 2026-08-27 18:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0005_alter_equipment_current_client_and_more"),
        ("operations", "0005_deactivate_test_duplicate_locations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cleaning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("performed_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("next_due_at", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cleanings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cleanings",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Movement associado, quando a higienização coincidiu com uma movimentação física relevante.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cleanings",
                        to="operations.movement",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cleanings_responsible",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "higienização",
                "verbose_name_plural": "higienizações",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalMaintenance",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("PREVENTIVA", "Preventiva"),
                            ("CORRETIVA", "Corretiva"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTA", "Aberta"),
                            ("CONCLUIDA", "Concluída"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ABERTA",
                        max_length=20,
                    ),
                ),
                ("diagnosis", models.TextField(blank=True)),
                ("service_performed", models.TextField(blank=True)),
                (
                    "condition_before",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BOM", "Bom"),
                            ("MEDIO", "Médio"),
                            ("RUIM", "Ruim"),
                            ("INUTILIZAVEL", "Inutilizável"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "condition_after",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BOM", "Bom"),
                            ("MEDIO", "Médio"),
                            ("RUIM", "Ruim"),
                            ("INUTILIZAVEL", "Inutilizável"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status_before",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("EM_OPERACAO", "Em operação"),
                            ("MANUTENCAO", "Manutenção"),
                            ("INATIVO", "Inativo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("next_due_at", models.DateField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departure_movement",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Movement ENVIO_MANUTENCAO associado, quando a manutenção envolveu saída física do equipamento.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="operations.movement",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_movement",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Movement de retorno (RETORNO_MANUTENCAO ou RETORNO_ESTOQUE) associado, quando houver.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="operations.movement",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical manutenção",
                "verbose_name_plural": "historical manutenções",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("PREVENTIVA", "Preventiva"),
                            ("CORRETIVA", "Corretiva"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTA", "Aberta"),
                            ("CONCLUIDA", "Concluída"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ABERTA",
                        max_length=20,
                    ),
                ),
                ("diagnosis", models.TextField(blank=True)),
                ("service_performed", models.TextField(blank=True)),
                (
                    "condition_before",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BOM", "Bom"),
                            ("MEDIO", "Médio"),
                            ("RUIM", "Ruim"),
                            ("INUTILIZAVEL", "Inutilizável"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "condition_after",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BOM", "Bom"),
                            ("MEDIO", "Médio"),
                            ("RUIM", "Ruim"),
                            ("INUTILIZAVEL", "Inutilizável"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status_before",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("EM_OPERACAO", "Em operação"),
                            ("MANUTENCAO", "Manutenção"),
                            ("INATIVO", "Inativo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("next_due_at", models.DateField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenances_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departure_movement",
                    models.OneToOneField(
                        blank=True,
                        help_text="Movement ENVIO_MANUTENCAO associado, quando a manutenção envolveu saída física do equipamento.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_as_departure",
                        to="operations.movement",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenances",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenances_responsible",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_movement",
                    models.OneToOneField(
                        blank=True,
                        help_text="Movement de retorno (RETORNO_MANUTENCAO ou RETORNO_ESTOQUE) associado, quando houver.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_as_return",
                        to="operations.movement",
                    ),
                ),
            ],
            options={
                "verbose_name": "manutenção",
                "verbose_name_plural": "manutenções",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="maintenance",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "CONCLUIDA"), _negated=True),
                    models.Q(("service_performed", ""), _negated=True),
                    _connector="OR",
                ),
                name="maintenance_conclusao_exige_servico",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenance",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("closed_at__isnull", True), ("status", "ABERTA")),
                    models.Q(
                        models.Q(("status", "ABERTA"), _negated=True),
                        ("closed_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="maintenance_closed_at_coerente_com_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ABERTA")),
                fields=("equipment",),
                name="uniq_maintenance_aberta_por_equipamento",
            ),
        ),
    ]
