# Generated by Django 5.0.14 on 2026-08-27 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_maintenance_aberta_ativa_constraint"),
        ("operations", "0005_deactivate_test_duplicate_locations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleaning",
            name="movement",
            field=models.ForeignKey(
                blank=True,
                help_text="Movement associado, quando a higienização coincidiu com uma movimentação física relevante. Qualquer MovementType é aceito (não há regra de domínio que restrinja o tipo) — só o vínculo de equipamento é obrigatório: apps.maintenance.services.create_cleaning() rejeita um Movement de outro equipamento.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cleanings",
                to="operations.movement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmaintenance",
            name="departure_movement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Movement ENVIO_MANUTENCAO associado, quando a manutenção envolveu saída física do equipamento. Validação completa (mesmo equipamento, tipo, não reclamado por outra ficha, coerência cronológica) é responsabilidade de apps.maintenance.services._validate_departure_movement() — nunca confiar só neste campo/OneToOneField para integridade de domínio.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="operations.movement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmaintenance",
            name="return_movement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Movement de retorno (RETORNO_MANUTENCAO ou RETORNO_ESTOQUE) associado, quando houver. Validação completa (mesmo equipamento, tipo, não reclamado por outra ficha, posterior à abertura e ao departure_movement, RETORNO_MANUTENCAO exige departure_movement) é responsabilidade de apps.maintenance.services._validate_return_movement() — nunca confiar só neste campo/OneToOneField para integridade de domínio.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="operations.movement",
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="departure_movement",
            field=models.OneToOneField(
                blank=True,
                help_text="Movement ENVIO_MANUTENCAO associado, quando a manutenção envolveu saída física do equipamento. Validação completa (mesmo equipamento, tipo, não reclamado por outra ficha, coerência cronológica) é responsabilidade de apps.maintenance.services._validate_departure_movement() — nunca confiar só neste campo/OneToOneField para integridade de domínio.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_as_departure",
                to="operations.movement",
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="return_movement",
            field=models.OneToOneField(
                blank=True,
                help_text="Movement de retorno (RETORNO_MANUTENCAO ou RETORNO_ESTOQUE) associado, quando houver. Validação completa (mesmo equipamento, tipo, não reclamado por outra ficha, posterior à abertura e ao departure_movement, RETORNO_MANUTENCAO exige departure_movement) é responsabilidade de apps.maintenance.services._validate_return_movement() — nunca confiar só neste campo/OneToOneField para integridade de domínio.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_as_return",
                to="operations.movement",
            ),
        ),
    ]
