# Generated by Django 5.0.14 on 2026-09-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_alter_cleaning_movement_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maintenance",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "view_maintenance_and_cleaning",
                        "Pode ver manutenção/higienização",
                    )
                ],
                "verbose_name": "manutenção",
                "verbose_name_plural": "manutenções",
            },
        ),
    ]
