# Generated by Django 5.0.14 on 2026-09-10 19:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0005_seed_cargo_architecture_base"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommercialSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordem de exibição nas listas/seletores."
                    ),
                ),
            ],
            options={
                "verbose_name": "origem comercial",
                "verbose_name_plural": "origens comerciais",
                "ordering": ["order", "name"],
                "permissions": [
                    (
                        "manage_commercial_settings",
                        "Pode gerenciar configurações comerciais (origens, etapas, motivos de perda)",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LossReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordem de exibição nas listas/seletores."
                    ),
                ),
            ],
            options={
                "verbose_name": "motivo de perda",
                "verbose_name_plural": "motivos de perda",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordem de exibição no funil."
                    ),
                ),
                (
                    "is_won",
                    models.BooleanField(
                        default=False, help_text="Etapa representa oportunidade GANHA."
                    ),
                ),
                (
                    "is_lost",
                    models.BooleanField(
                        default=False,
                        help_text="Etapa representa oportunidade PERDIDA.",
                    ),
                ),
            ],
            options={
                "verbose_name": "etapa da oportunidade",
                "verbose_name_plural": "etapas da oportunidade",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityStageChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Observação/motivo opcional da transição."
                    ),
                ),
            ],
            options={
                "verbose_name": "histórico de etapa",
                "verbose_name_plural": "histórico de etapas",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalOpportunity",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("title", models.CharField(max_length=200)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("LOCACAO", "Locação"),
                            ("VENDA", "Venda"),
                            ("SERVICO", "Serviço"),
                        ],
                        max_length=10,
                    ),
                ),
                ("expected_close_date", models.DateField(blank=True, null=True)),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor estimado (Decimal — nunca float).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("loss_notes", models.TextField(blank=True)),
                ("won_at", models.DateTimeField(blank=True, null=True)),
                ("lost_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor efetivo no fechamento (ganho) — Decimal, nunca float.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Responsável comercial pela oportunidade.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crm.commercialsource",
                    ),
                ),
                (
                    "loss_reason",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crm.lossreason",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical oportunidade",
                "verbose_name_plural": "historical oportunidades",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("LOCACAO", "Locação"),
                            ("VENDA", "Venda"),
                            ("SERVICO", "Serviço"),
                        ],
                        max_length=10,
                    ),
                ),
                ("expected_close_date", models.DateField(blank=True, null=True)),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor estimado (Decimal — nunca float).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("loss_notes", models.TextField(blank=True)),
                ("won_at", models.DateTimeField(blank=True, null=True)),
                ("lost_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor efetivo no fechamento (ganho) — Decimal, nunca float.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commercial_opportunities_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loss_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="crm.lossreason",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Responsável comercial pela oportunidade.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commercial_opportunities_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="crm.commercialsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "oportunidade",
                "verbose_name_plural": "oportunidades",
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_opportunities", "Pode ver oportunidades"),
                    ("add_opportunities", "Pode criar oportunidades"),
                    ("change_opportunities", "Pode editar oportunidades"),
                    (
                        "change_opportunity_stage",
                        "Pode alterar etapa/ganho/perda de oportunidades",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommercialActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("LIGACAO", "Ligação"),
                            ("WHATSAPP", "WhatsApp"),
                            ("EMAIL", "E-mail"),
                            ("REUNIAO", "Reunião"),
                            ("VISITA", "Visita"),
                            ("OBSERVACAO", "Observação"),
                            ("FOLLOW_UP", "Follow-up"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando a interação de fato aconteceu.",
                        null=True,
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True,
                        help_text="Próximo passo agendado — consumido pela futura Agenda Central.",
                        null=True,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commercial_activities_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="crm.opportunity",
                    ),
                ),
            ],
            options={
                "verbose_name": "atividade comercial",
                "verbose_name_plural": "atividades comerciais",
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_commercial_activities", "Pode ver atividades comerciais"),
                    (
                        "add_commercial_activities",
                        "Pode registrar atividades comerciais",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="opportunitystage",
            constraint=models.CheckConstraint(
                check=models.Q(("is_won", True), ("is_lost", True), _negated=True),
                name="crm_stage_not_won_and_lost_simultaneously",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opportunities",
                to="crm.opportunitystage",
            ),
        ),
        migrations.AddField(
            model_name="historicalopportunity",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="crm.opportunitystage",
            ),
        ),
        migrations.AddField(
            model_name="opportunitystagechange",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="crm_stage_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="opportunitystagechange",
            name="from_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stage_changes_from",
                to="crm.opportunitystage",
            ),
        ),
        migrations.AddField(
            model_name="opportunitystagechange",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stage_changes",
                to="crm.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="opportunitystagechange",
            name="to_stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stage_changes_to",
                to="crm.opportunitystage",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("won_at__isnull", False), ("lost_at__isnull", False), _negated=True
                ),
                name="crm_opportunity_not_won_and_lost_simultaneously",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("estimated_value__isnull", True),
                    ("estimated_value__gte", 0),
                    _connector="OR",
                ),
                name="crm_opportunity_estimated_value_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("closed_value__isnull", True),
                    ("closed_value__gte", 0),
                    _connector="OR",
                ),
                name="crm_opportunity_closed_value_not_negative",
            ),
        ),
    ]
