# Generated by Django 5.0.14 on 2026-09-14 13:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_seed_cargo_architecture_base"),
        ("crm", "0001_initial"),
        ("operations", "0006_seed_cargo_architecture_base"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberingCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=30, unique=True)),
                ("last_value", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "contador de numeração",
                "verbose_name_plural": "contadores de numeração",
            },
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposals_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="crm.opportunity",
                    ),
                ),
            ],
            options={
                "verbose_name": "proposta",
                "verbose_name_plural": "propostas",
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "issue_proposal_documents",
                        "Pode emitir documentos de proposta (Proposta Comercial)",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProposalVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("ISSUED", "Emitida"),
                            ("ACCEPTED", "Aceita"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "price_table_label",
                    models.CharField(
                        blank=True,
                        help_text="Texto livre por enquanto — ponto de extensão para a futura PriceTable (seção 19/102, não implementada nesta etapa).",
                        max_length=100,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PIX", "PIX"),
                            ("BOLETO", "Boleto"),
                            ("CARTAO", "Cartão"),
                            ("TRANSFERENCIA", "Transferência bancária"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_method_other",
                    models.CharField(
                        blank=True,
                        help_text="Usado quando 'Forma de pagamento' = Outro.",
                        max_length=100,
                    ),
                ),
                (
                    "payment_condition",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: 'À vista', '28 dias' — texto livre (seção 31).",
                        max_length=150,
                    ),
                ),
                ("contracted_start_date", models.DateField(blank=True, null=True)),
                ("contracted_end_date", models.DateField(blank=True, null=True)),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                ("expected_delivery_time", models.TimeField(blank=True, null=True)),
                ("expected_pickup_date", models.DateField(blank=True, null=True)),
                ("expected_pickup_time", models.TimeField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "general_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Valor monetário, não percentual (seção 25).",
                        max_digits=12,
                    ),
                ),
                (
                    "interest_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Juros (seção 26).",
                        max_digits=12,
                    ),
                ),
                (
                    "freight_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("special_clauses", models.TextField(blank=True)),
                ("payment_info_notes", models.TextField(blank=True)),
                ("general_notes", models.TextField(blank=True)),
                ("client_name_snapshot", models.CharField(blank=True, max_length=200)),
                (
                    "client_document_snapshot",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "client_contact_snapshot",
                    models.CharField(blank=True, max_length=150),
                ),
                ("client_phone_snapshot", models.CharField(blank=True, max_length=30)),
                ("client_email_snapshot", models.CharField(blank=True, max_length=254)),
                ("client_address_snapshot", models.TextField(blank=True)),
                ("company_name_snapshot", models.CharField(blank=True, max_length=200)),
                (
                    "company_document_snapshot",
                    models.CharField(blank=True, max_length=20),
                ),
                ("company_address_snapshot", models.TextField(blank=True)),
                ("company_phone_snapshot", models.CharField(blank=True, max_length=30)),
                (
                    "company_email_snapshot",
                    models.CharField(blank=True, max_length=254),
                ),
                (
                    "seller_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Responsável/vendedor (owner da Opportunity) no momento da emissão (seção 40).",
                        max_length=150,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposal_versions_accepted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposal_versions",
                        to="operations.location",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposal_versions_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="crm.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "versão da proposta",
                "verbose_name_plural": "versões da proposta",
                "ordering": ["proposal_id", "version_number"],
                "permissions": [
                    (
                        "generate_contract",
                        "Pode gerar contratos a partir de uma proposta",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProposalItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description_snapshot", models.CharField(blank=True, max_length=200)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "item_discount_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "equipment_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposal_items",
                        to="catalog.equipmentmodel",
                    ),
                ),
                (
                    "proposal_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="crm.proposalversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "item da proposta",
                "verbose_name_plural": "itens da proposta",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("legal_text_is_placeholder", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="crm.proposalversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "contrato",
                "verbose_name_plural": "contratos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="proposalversion",
            constraint=models.UniqueConstraint(
                fields=("proposal", "version_number"),
                name="uniq_proposal_version_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposalversion",
            constraint=models.CheckConstraint(
                check=models.Q(("subtotal__gte", 0)),
                name="proposal_version_subtotal_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposalversion",
            constraint=models.CheckConstraint(
                check=models.Q(("total__gte", 0)),
                name="proposal_version_total_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposalversion",
            constraint=models.CheckConstraint(
                check=models.Q(("general_discount__gte", 0)),
                name="proposal_version_general_discount_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposalversion",
            constraint=models.CheckConstraint(
                check=models.Q(("interest_amount__gte", 0)),
                name="proposal_version_interest_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposalversion",
            constraint=models.CheckConstraint(
                check=models.Q(("freight_amount__gte", 0)),
                name="proposal_version_freight_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposalitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)),
                name="proposal_item_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposalitem",
            constraint=models.CheckConstraint(
                check=models.Q(("unit_price__gte", 0)),
                name="proposal_item_unit_price_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposalitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("item_discount_percent__gte", 0),
                    ("item_discount_percent__lte", 100),
                ),
                name="proposal_item_discount_percent_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposalitem",
            constraint=models.CheckConstraint(
                check=models.Q(("line_total__gte", 0)),
                name="proposal_item_line_total_not_negative",
            ),
        ),
    ]
