# Generated by Django 5.0.14 on 2026-09-14 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_item_discount_percent_to_amount"),
        ("equipment", "0006_seed_cargo_architecture_base"),
        ("operations", "0006_seed_cargo_architecture_base"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                ("unlinked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunity_links",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crm_equipment_links_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="operations.movement",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_links",
                        to="crm.opportunity",
                    ),
                ),
                (
                    "unlinked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crm_equipment_links_ended",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unlinked_movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="operations.movement",
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo de equipamento",
                "verbose_name_plural": "vínculos de equipamento",
                "ordering": ["-linked_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="opportunityequipment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("unlinked_at__isnull", True)),
                fields=("equipment",),
                name="one_active_link_per_equipment",
            ),
        ),
    ]
