# Generated by Django 5.0.14 on 2026-09-15 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_seed_cargo_architecture_base"),
        ("crm", "0007_opportunity_equipment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordem de exibição nos seletores."
                    ),
                ),
                (
                    "unit_label",
                    models.CharField(
                        default="hora",
                        help_text="Rótulo da unidade comercial, ex.: 'hora', 'diária', 'un'.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "serviço comercial",
                "verbose_name_plural": "catálogo de serviços comerciais",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="proposalitem",
            name="item_type",
            field=models.CharField(
                choices=[("EQUIPAMENTO", "Equipamento"), ("SERVICO", "Serviço")],
                default="EQUIPAMENTO",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="proposalitem",
            name="unit_label_snapshot",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="proposalitem",
            name="equipment_model",
            field=models.ForeignKey(
                blank=True,
                help_text="Preenchido quando item_type=EQUIPAMENTO — nunca junto com 'service'.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proposal_items",
                to="catalog.equipmentmodel",
            ),
        ),
        migrations.AddField(
            model_name="proposalitem",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="Preenchido quando item_type=SERVICO — nunca junto com 'equipment_model'.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proposal_items",
                to="crm.servicecatalogitem",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposalitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("equipment_model__isnull", False),
                        ("item_type", "EQUIPAMENTO"),
                        ("service__isnull", True),
                    ),
                    models.Q(
                        ("equipment_model__isnull", True),
                        ("item_type", "SERVICO"),
                        ("service__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="proposal_item_type_matches_single_reference",
            ),
        ),
    ]
