# Generated by Django 5.0.14 on 2026-09-16 17:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_seed_cargo_architecture_base"),
        ("crm", "0009_seed_hora_tecnica"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("LOCACAO", "Locação"),
                            ("VENDA", "Venda"),
                            ("SERVICO", "Serviço"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Preenchido automaticamente ('Tabela de Locação', etc.) quando vazio — texto livre é só ponto de extensão futuro, não editável na V1.",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "tabela de preços",
                "verbose_name_plural": "tabelas de preços",
                "ordering": ["business_type"],
                "permissions": [
                    ("view_price_table", "Pode ver a Tabela de Preços"),
                    ("change_price_table", "Pode editar valores da Tabela de Preços"),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalPriceTableItem",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "equipment_model",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Preenchido XOR com 'service' — nunca os dois, nunca nenhum.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalog.equipmentmodel",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Preenchido XOR com 'equipment_model' — nunca os dois, nunca nenhum.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crm.servicecatalogitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "price_table",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crm.pricetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical item da tabela de preços",
                "verbose_name_plural": "historical itens da tabela de preços",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PriceTableItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "equipment_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preenchido XOR com 'service' — nunca os dois, nunca nenhum.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_table_items",
                        to="catalog.equipmentmodel",
                    ),
                ),
                (
                    "price_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="crm.pricetable",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preenchido XOR com 'equipment_model' — nunca os dois, nunca nenhum.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_table_items",
                        to="crm.servicecatalogitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "item da tabela de preços",
                "verbose_name_plural": "itens da tabela de preços",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="pricetableitem",
            constraint=models.CheckConstraint(
                check=models.Q(("unit_price__gte", 0)),
                name="price_table_item_unit_price_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricetableitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("equipment_model__isnull", False), ("service__isnull", True)
                    ),
                    models.Q(
                        ("equipment_model__isnull", True), ("service__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="price_table_item_xor_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricetableitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("equipment_model__isnull", False)),
                fields=("price_table", "equipment_model"),
                name="unique_price_table_equipment_model",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricetableitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("service__isnull", False)),
                fields=("price_table", "service"),
                name="unique_price_table_service",
            ),
        ),
    ]
