# Generated by Django 5.0.14 on 2026-09-16 18:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_price_table_v1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommercialPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("LOCACAO", "Locação"),
                            ("VENDA", "Venda"),
                            ("SERVICO", "Serviço"),
                        ],
                        default="LOCACAO",
                        max_length=10,
                    ),
                ),
                (
                    "pricing_mode",
                    models.CharField(
                        choices=[
                            ("ITEM_TERM", "Preço por item × prazo"),
                            ("BUNDLE", "Pacote fechado (combo)"),
                        ],
                        default="ITEM_TERM",
                        max_length=15,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem de exibição nas abas/seletores de plano.",
                    ),
                ),
            ],
            options={
                "verbose_name": "plano comercial",
                "verbose_name_plural": "planos comerciais",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CommercialTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Texto de exibição, ex.: '7 dias'. Preenchido automaticamente quando vazio.",
                        max_length=50,
                    ),
                ),
                ("duration_value", models.PositiveIntegerField()),
                (
                    "duration_unit",
                    models.CharField(
                        choices=[("DIAS", "dias"), ("MESES", "meses")], max_length=5
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordem de exibição das colunas na matriz."
                    ),
                ),
                (
                    "commercial_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="crm.commercialplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "prazo comercial",
                "verbose_name_plural": "prazos comerciais",
                "ordering": ["commercial_plan_id", "order", "duration_value"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalPriceTableRate",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "billing_mode",
                    models.CharField(
                        choices=[
                            ("TERM_TOTAL", "Valor total do prazo"),
                            ("MONTHLY", "Valor mensal"),
                        ],
                        default="TERM_TOTAL",
                        max_length=10,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "commercial_plan",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crm.commercialplan",
                    ),
                ),
                (
                    "commercial_term",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crm.commercialterm",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "price_table_item",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crm.pricetableitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical valor da matriz de preços de locação",
                "verbose_name_plural": "historical valores da matriz de preços de locação",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PriceTableRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "billing_mode",
                    models.CharField(
                        choices=[
                            ("TERM_TOTAL", "Valor total do prazo"),
                            ("MONTHLY", "Valor mensal"),
                        ],
                        default="TERM_TOTAL",
                        max_length=10,
                    ),
                ),
                (
                    "commercial_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates",
                        to="crm.commercialplan",
                    ),
                ),
                (
                    "commercial_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates",
                        to="crm.commercialterm",
                    ),
                ),
                (
                    "price_table_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="crm.pricetableitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "valor da matriz de preços de locação",
                "verbose_name_plural": "valores da matriz de preços de locação",
                "ordering": ["price_table_item_id", "commercial_term_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="commercialterm",
            constraint=models.UniqueConstraint(
                fields=("commercial_plan", "label"),
                name="uniq_commercial_term_label_per_plan",
            ),
        ),
        migrations.AddConstraint(
            model_name="commercialterm",
            constraint=models.CheckConstraint(
                check=models.Q(("duration_value__gt", 0)),
                name="commercial_term_duration_value_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricetablerate",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gte", 0)),
                name="price_table_rate_amount_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricetablerate",
            constraint=models.UniqueConstraint(
                fields=("price_table_item", "commercial_plan", "commercial_term"),
                name="uniq_price_table_rate_item_plan_term",
            ),
        ),
    ]
