# Generated by Django 5.0.14 on 2026-09-16 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_seed_cargo_architecture_base"),
        ("crm", "0012_seed_commercial_plans_terms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pricetableitem",
            name="price_table_item_unit_price_not_negative",
        ),
        migrations.AlterField(
            model_name="historicalpricetableitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pricetableitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="pricetableitem",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("unit_price__isnull", True),
                    ("unit_price__gte", 0),
                    _connector="OR",
                ),
                name="price_table_item_unit_price_not_negative",
            ),
        ),
    ]
