# Generated by Django 5.0.14 on 2026-09-23 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0013_rodada1_price_table_item_unit_price_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposalversion",
            name="client_company_name_snapshot",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="proposalversion",
            name="client_trade_name_snapshot",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="proposalversion",
            name="client_type_snapshot",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="proposalversion",
            name="commercial_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proposal_versions",
                to="crm.commercialplan",
            ),
        ),
        migrations.AddField(
            model_name="proposalversion",
            name="commercial_plan_name_snapshot",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="proposalversion",
            name="company_city_snapshot",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="proposalversion",
            name="company_uf_snapshot",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="proposalversion",
            name="event_name",
            field=models.CharField(
                blank=True,
                help_text="Ex.: 'Expoingá 2027', 'Casamento XYZ' — opcional (seção 27).",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="proposalversion",
            name="onsite_responsible_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="proposalversion",
            name="onsite_responsible_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="proposalversion",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PIX", "PIX"),
                    ("BOLETO", "Boleto"),
                    ("CARTAO", "Cartão"),
                    ("TRANSFERENCIA", "Transferência bancária"),
                    ("DINHEIRO", "Dinheiro"),
                    ("OUTRO", "Outro"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProposalVersionInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text='Ordem de exibição ("Parcela 1", "Parcela 2"...) — único dentro da versão.'
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("PIX", "PIX"),
                            ("BOLETO", "Boleto"),
                            ("CARTAO", "Cartão"),
                            ("TRANSFERENCIA", "Transferência bancária"),
                            ("DINHEIRO", "Dinheiro"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_method_other",
                    models.CharField(
                        blank=True,
                        help_text="Usado quando 'Forma de pagamento' = Outro.",
                        max_length=100,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="crm.proposalversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "parcela da proposta",
                "verbose_name_plural": "parcelas da proposta",
                "ordering": ["proposal_version_id", "sequence"],
            },
        ),
        migrations.AddConstraint(
            model_name="proposalversioninstallment",
            constraint=models.UniqueConstraint(
                fields=("proposal_version", "sequence"),
                name="uniq_proposal_installment_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposalversioninstallment",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)),
                name="proposal_installment_amount_positive",
            ),
        ),
    ]
