# Generated by Django 5.0.14 on 2026-08-20 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ESTOQUE", "Estoque/Barracão"),
                            ("CLIENTE", "Cliente"),
                            ("MANUTENCAO", "Manutenção"),
                            ("TRANSPORTE", "Transporte"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preenchido quando type=CLIENTE.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "localização",
                "verbose_name_plural": "localizações",
                "ordering": ["name"],
            },
        ),
    ]
