# Generated by Django 5.0.14 on 2026-08-25 14:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_historicalclient_remove_client_address_and_more"),
        ("core", "0001_initial"),
        ("equipment", "0005_alter_equipment_current_client_and_more"),
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLocation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ESTOQUE", "Estoque/Barracão"),
                            ("CLIENTE", "Cliente"),
                            ("MANUTENCAO", "Manutenção"),
                            ("TRANSPORTE", "Transporte"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical localização",
                "verbose_name_plural": "historical localizações",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("INSTALACAO", "Instalação"),
                            ("RETIRADA", "Retirada"),
                            ("TRANSFERENCIA", "Transferência"),
                            ("RETORNO_ESTOQUE", "Retorno ao estoque"),
                            ("ENVIO_MANUTENCAO", "Envio para manutenção"),
                            ("RETORNO_MANUTENCAO", "Retorno da manutenção"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("origin_location_name", models.CharField(blank=True, max_length=150)),
                (
                    "destination_location_name",
                    models.CharField(blank=True, max_length=150),
                ),
                ("origin_client_name", models.CharField(blank=True, max_length=200)),
                (
                    "destination_client_name",
                    models.CharField(blank=True, max_length=200),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "movimentação",
                "verbose_name_plural": "movimentações",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="location_operational_for",
                to="core.address",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Preenchido quando type=CLIENTE — cada unidade/local do cliente é uma Location própria.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="clients.client",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("client__isnull", False), ("type", "CLIENTE")),
                    models.Q(
                        models.Q(("type", "CLIENTE"), _negated=True),
                        ("client__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="location_client_matches_type",
            ),
        ),
        migrations.AddField(
            model_name="historicallocation",
            name="address",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.address",
            ),
        ),
        migrations.AddField(
            model_name="historicallocation",
            name="client",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Preenchido quando type=CLIENTE — cada unidade/local do cliente é uma Location própria.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="historicallocation",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movement",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movement",
            name="destination_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements_to",
                to="operations.location",
            ),
        ),
        migrations.AddField(
            model_name="movement",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="equipment.equipment",
            ),
        ),
        migrations.AddField(
            model_name="movement",
            name="origin_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements_from",
                to="operations.location",
            ),
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("movement_type", "OUTRO"), _negated=True),
                    models.Q(("reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="movement_outro_requires_reason",
            ),
        ),
    ]
