# Generated by Django 5.0.14 on 2026-09-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0005_deactivate_test_duplicate_locations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["name"],
                "permissions": [
                    (
                        "view_diagnostics",
                        "Pode ver diagnósticos internos (ex.: locais duplicados)",
                    ),
                    ("manage_locations", "Pode gerenciar locais"),
                ],
                "verbose_name": "localização",
                "verbose_name_plural": "localizações",
            },
        ),
        migrations.AlterModelOptions(
            name="movement",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "register_operations",
                        "Pode registrar operações (manutenção/higienização/movimentação)",
                    ),
                    ("view_movements", "Pode ver movimentações"),
                ],
                "verbose_name": "movimentação",
                "verbose_name_plural": "movimentações",
            },
        ),
    ]
