# Generated by Django 5.0.14 on 2026-08-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("company_name", models.CharField(max_length=200)),
                ("trade_name", models.CharField(blank=True, max_length=200)),
                (
                    "document",
                    models.CharField(
                        blank=True,
                        help_text="CNPJ/CPF, quando aplicável.",
                        max_length=30,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("contact_name", models.CharField(blank=True, max_length=150)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
                "ordering": ["company_name"],
            },
        ),
    ]
