# Generated by Django 5.0.14 on 2026-08-25 14:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalClient",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "client_type",
                    models.CharField(
                        choices=[("PJ", "Pessoa Jurídica"), ("PF", "Pessoa Física")],
                        default="PJ",
                        max_length=2,
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        blank=True,
                        help_text="CNPJ (ou, futuramente, CPF). Só dígitos, validado no backend.",
                        max_length=18,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(help_text="Razão social.", max_length=200),
                ),
                (
                    "trade_name",
                    models.CharField(
                        blank=True, help_text="Nome fantasia.", max_length=200
                    ),
                ),
                (
                    "registration_status",
                    models.CharField(
                        blank=True,
                        help_text="Situação cadastral (ex.: 'ATIVA'), quando disponível pela consulta de CNPJ.",
                        max_length=60,
                    ),
                ),
                (
                    "state_registration",
                    models.CharField(
                        blank=True,
                        help_text="Inscrição estadual, se aplicável.",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, help_text="Contato responsável.", max_length=150
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cliente",
                "verbose_name_plural": "historical clientes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name="client",
            name="address",
        ),
        migrations.RemoveField(
            model_name="client",
            name="city",
        ),
        migrations.RemoveField(
            model_name="client",
            name="state",
        ),
        migrations.AddField(
            model_name="client",
            name="client_type",
            field=models.CharField(
                choices=[("PJ", "Pessoa Jurídica"), ("PF", "Pessoa Física")],
                default="PJ",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="fiscal_address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_fiscal_for",
                to="core.address",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="registration_status",
            field=models.CharField(
                blank=True,
                help_text="Situação cadastral (ex.: 'ATIVA'), quando disponível pela consulta de CNPJ.",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="state_registration",
            field=models.CharField(
                blank=True, help_text="Inscrição estadual, se aplicável.", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="company_name",
            field=models.CharField(help_text="Razão social.", max_length=200),
        ),
        migrations.AlterField(
            model_name="client",
            name="contact_name",
            field=models.CharField(
                blank=True, help_text="Contato responsável.", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="document",
            field=models.CharField(
                blank=True,
                help_text="CNPJ (ou, futuramente, CPF). Só dígitos, validado no backend.",
                max_length=18,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="trade_name",
            field=models.CharField(
                blank=True, help_text="Nome fantasia.", max_length=200
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                condition=models.Q(("document", ""), _negated=True),
                fields=("document",),
                name="uniq_client_document_when_present",
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="fiscal_address",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.address",
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
