# Generated by Django 5.0.14 on 2026-08-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_historicalclient_remove_client_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="company_name",
            field=models.CharField(
                blank=True, help_text="Razão social (opcional).", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="document",
            field=models.CharField(
                help_text="CNPJ (ou, futuramente, CPF). Só dígitos, validado no backend.",
                max_length=18,
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="company_name",
            field=models.CharField(
                blank=True, help_text="Razão social (opcional).", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="document",
            field=models.CharField(
                help_text="CNPJ (ou, futuramente, CPF). Só dígitos, validado no backend.",
                max_length=18,
            ),
        ),
    ]
