# Generated by Django 5.0.14 on 2026-09-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_client_company_name_alter_client_document_and_more"),
        ("core", "0002_consumedsubmissiontoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="auvo_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código do cliente no Auvo (importação/rastreabilidade).",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="billing_email",
            field=models.EmailField(
                blank=True,
                help_text="E-mail de cobrança, se distinto do e-mail de contato.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="external_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código externo (Auvo).",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="icms_taxpayer",
            field=models.CharField(
                blank=True,
                help_text="Contribuinte do ICMS (valor original, sem interpretação).",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="municipal_registration",
            field=models.CharField(
                blank=True,
                help_text="Inscrição municipal, se aplicável.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="auvo_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código do cliente no Auvo (importação/rastreabilidade).",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="billing_email",
            field=models.EmailField(
                blank=True,
                help_text="E-mail de cobrança, se distinto do e-mail de contato.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="external_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código externo (Auvo).",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="icms_taxpayer",
            field=models.CharField(
                blank=True,
                help_text="Contribuinte do ICMS (valor original, sem interpretação).",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="municipal_registration",
            field=models.CharField(
                blank=True,
                help_text="Inscrição municipal, se aplicável.",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                condition=models.Q(("auvo_code", ""), _negated=True),
                fields=("auvo_code",),
                name="uniq_client_auvo_code_when_present",
            ),
        ),
    ]
