# Generated by Django 5.0.14 on 2026-09-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_client_auvo_code_client_billing_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["company_name"],
                "permissions": [
                    ("view_clients", "Pode ver clientes"),
                    ("manage_clients", "Pode gerenciar clientes"),
                    ("import_clients", "Pode importar clientes (Auvo)"),
                ],
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
            },
        ),
    ]
