# Generated by Django 5.0.14 on 2026-08-20 12:55

import django.core.validators
import django.db.models.deletion
import re
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nome de exibição, ex.: 'NI23 Big Tank'.",
                        max_length=150,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Ex.: AQCP, NI23BT. Usado na composição do patrimônio. Trava para edição assim que houver um equipamento vinculado.",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="O código deve ter de 2 a 20 caracteres, só letras maiúsculas e números, sem espaços.",
                                regex=re.compile("^[A-Z0-9]{2,20}$"),
                            )
                        ],
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=150)),
                (
                    "specs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Campos livres por categoria (BTUs, voltagem, etc.).",
                    ),
                ),
                (
                    "last_sequence",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="models",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "modelo de equipamento",
                "verbose_name_plural": "modelos de equipamento",
                "ordering": ["category__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEquipmentModel",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nome de exibição, ex.: 'NI23 Big Tank'.",
                        max_length=150,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Ex.: AQCP, NI23BT. Usado na composição do patrimônio. Trava para edição assim que houver um equipamento vinculado.",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="O código deve ter de 2 a 20 caracteres, só letras maiúsculas e números, sem espaços.",
                                regex=re.compile("^[A-Z0-9]{2,20}$"),
                            )
                        ],
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=150)),
                (
                    "specs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Campos livres por categoria (BTUs, voltagem, etc.).",
                    ),
                ),
                (
                    "last_sequence",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalog.category",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical modelo de equipamento",
                "verbose_name_plural": "historical modelos de equipamento",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
