# Generated by Django 5.0.14 on 2026-09-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_historicalequipmentmodel_history_change_reason"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipmentmodel",
            options={
                "ordering": ["category__name", "name"],
                "permissions": [
                    (
                        "manage_catalog",
                        "Pode gerenciar catálogo (categorias e modelos de equipamento)",
                    ),
                    (
                        "reclassify_equipment_model",
                        "Pode reclassificar modelo de equipamento",
                    ),
                ],
                "verbose_name": "modelo de equipamento",
                "verbose_name_plural": "modelos de equipamento",
            },
        ),
    ]
